# (C) copyrights 2019 SuperDARN Canada, University of Saskatchewan
#                2021 SuperDARN, Virginia Polytechnic Institute & State University
# authors: Marina Schmidt, SuperDARN Canada
#          Kevin Sterne, VT
site_name: RST Documentation
repo_url: https://github.com/superdarn/rst
theme: readthedocs
markdown_extensions:
    - extra
    - admonition
    - toc

pages:
- Home: index.md
- About: about.md
- Installation:
        - Linux: user_guide/linux_install.md
        - MacOSX: user_guide/mac_install.md
- SuperDARN Data:
    - Accessing Data: user_guide/data.md
    - Citing Data: user_guide/citing.md
    - Filename Formats: references/general/filename.md
    - Radar Identifier: references/general/radar_id.md
- RST Tutorials: 
    - Data Processing: 
            - RAWACF to FITACF: user_guide/make_fit.md
            - FITACF to GRID: user_guide/make_grid.md
            - GRID to MAP: user_guide/map_grid.md
    - Plotting Data: 
            - Range-time Plots: user_guide/time_plot.md
            - Field of View Plots: user_guide/fov_plot.md
            - Field Plots: user_guide/field_plot.md
            - Grid Plots: user_guide/grid_plot.md
            - Convection Plots: user_guide/map_plot.md
            - Customized Colors: user_guide/colors.md
- RST Developers Guide:
    - Copyrights and Licensing: developers_guide/copyright_license.md 
    - Data Structures in C:
            - cFit: developers_guide/cfit_struct_c.md
            - FitACF: developers_guide/fitacf_struct_c.md
            - Grid: developers_guide/grid_struct_c.md
            - IQDat: developers_guide/iqdat_struct_c.md
            - Map (cnvmap): developers_guide/cnvmap_struct_c.md
            - Radar Parameter Block: developers_guide/radar_parameter_c.md
            - RawACF: developers_guide/rawacf_struct_c.md
    - Data Structure in IDL:
            - FitACF: developers_guide/fitacf_struct_idl.md
            - Grid: developers_guide/grid_struct_idl.md
            - IQDat: developers_guide/iqdat_struct_idl.md
            - Map (cnvmap): developers_guide/cnvmap_struct_idl.md
            - Radar Parameter Block: developers_guide/radar_parameter_idl.md
            - RawACF: developers_guide/rawacf_struct_idl.md
- SuperDARN Data Formats:
     - cFit Format: reference/general/cfit.md
     - Dmap Data: references/general/dmap_data.md
     - FitACF Format: references/general/fitacf.md
     - Grid Format: references/general/grid.md
     - IQDat Format: references/general/iqdat.md
     - Map Format: references/general/map.md
     - RawACF Format: references/general/rawacf.md
- Legacy Software:
     - Electric Field Data Structure for IDL: legacy_software/efield_struct_idl.md
     - rPlot Libraries: legacy_software/rPlot_lib.md
     - rPlot XML: legacy_software/rPlot_XML.md
